### ISSUE TITLE
Upgrade phpunit/php-code-coverage to 9.0

### ISSUE THREAD

**Issue by nreynis** [matthiasnoback/live-code-coverage#15]
This package dependencies prevent upgrading to phpunit 9.3.   
Being stuck with phpunit 9.2 is an issue because it also [lock us away from PHP8](https://github.com/sebastianbergmann/phpunit/issues/4373).

**Comment by matthiasnoback** [comment]
Makes sense, can you make a PR?

**Comment by nreynis** [comment]
I tried to give it a shot, but there's major BC in php-code-coverage.   
I'm not familiar with previous version, so I'll have to understand what each method was doing and how it maps to the new API. If I have some time I'll try to dig further, but I can't promise anything.

**Comment by nreynis** [comment]
Done!

**Comment by matthiasnoback** [comment]
Fixed by #16.

**Comment by matthiasnoback** [comment]
Thanks a lot Nicolas! I've added one other commit because I noticed that PHPUnit now has a FilterMapper that does the work of processing the files and directories etc. inside the <filter> config. So that saves us a few lines here.

**Comment by matthiasnoback** [comment]
By the way, I've released this as v1.4.0.
