### ISSUE TITLE
Use a dynamic coverage ID

### ISSUE THREAD

**Issue by matthiasnoback** [matthiasnoback/live-code-coverage#2]
This would make the coverage report more useful since on hover it will show which coverage runs covered a certain line.
Maybe it should be based on the request URI?

**Comment by Thijmen** [comment]
In my tests I write the current test-name to a Cookie and in my index.php I retrieve my cookie. In that way, you can archieve this too :-)

**Comment by matthiasnoback** [comment]
Thanks for the suggestion, I will try that for my current situation! I don't think now that this library needs to have more code for that. You can easily set up your own function to determine the coverage ID. Closing this issue now :)

**Comment by Thijmen** [comment]
I agree, and that's what makes this package so great! It gives a developer to implement it in their own way! :-)

**Comment by matthiasnoback** [comment]
Nice, thank you :)
